<template>
  <main class="min-h-0 flex-1 overflow-auto bg-slate-50 px-5 py-6">
    <div class="mx-auto w-full max-w-[1280px] space-y-4">
      <header class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs font-semibold text-blue-600">订单发布</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-900">订单打包上传 SVN</h2></div><span class="text-xs text-slate-500">每个项目单独确认分支，按顺序打包上传</span></header>

      <section class="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div class="flex flex-wrap items-center gap-2">
        <button class="selection-trigger min-w-[240px]" :disabled="store.running" @click="openSvnPicker('hospital')"><span>医院</span><b>{{ hospitalName || '搜索并选择医院' }}</b><i>⌄</i></button>
        <button class="selection-trigger min-w-[190px]" :disabled="store.running || !hospitalName" @click="openSvnPicker('order')"><span>订单号</span><b>{{ orderNo || '搜索并选择订单' }}</b><i>⌄</i></button>
        <div class="ml-auto flex items-center gap-2"><button class="secondary-btn" :disabled="store.running" @click="openProjectPicker">+ 选择项目</button><button class="run-btn !h-10 !px-5" :class="{ stop: store.running }" @click="store.running ? stopRun() : startBuild()">{{ store.running ? '停止构建' : '开始构建' }}</button></div>
      </div></section>

      <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><header class="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div class="flex items-center gap-2"><h3 class="text-sm font-bold text-slate-900">构建项目</h3><span class="text-xs text-slate-500">{{ selectedProjects.length }} 个已选择</span></div><button v-if="selectedProjects.length && !store.running" class="text-xs font-semibold text-blue-600 hover:text-blue-800" @click="openProjectPicker">编辑项目与分支</button></header>
        <div v-if="selectedProjects.length" class="divide-y divide-slate-100"><div v-for="item in selectedProjects" :key="item.name" class="flex items-center gap-3 px-4 py-2.5"><span class="grid h-7 w-7 place-items-center rounded-lg bg-blue-50 text-blue-600">◆</span><span class="min-w-0 flex-1 truncate text-sm font-semibold text-slate-800">{{ item.name }}</span><span class="branch-pill">{{ item.branch }}</span><span class="w-28 text-right text-xs font-medium" :class="queueClass(item.name)">{{ queueLabel(item.name) }}</span><button v-if="!store.running" class="text-lg leading-none text-slate-400 hover:text-red-500" title="移除项目" @click="removeProject(item.name)">×</button></div></div>
        <button v-else class="flex w-full items-center justify-center gap-2 px-4 py-6 text-sm text-slate-500 hover:bg-slate-50" @click="openProjectPicker"><span class="text-lg text-blue-600">＋</span> 搜索项目并选择对应分支</button>
      </section>

      <section class="overflow-hidden rounded-xl border border-slate-800 bg-[#0b1220] shadow-xl shadow-slate-900/10"><header class="flex flex-wrap items-center justify-between gap-2 border-b border-slate-700/80 px-4 py-3"><div><p class="font-mono text-xs font-bold text-sky-400">BUILD LIVE</p><p class="mt-1 text-sm font-semibold text-white">{{ activeProjectName }} <span class="font-normal text-slate-400">· {{ activeBranch }}</span></p></div><div class="text-right"><p class="text-xs" :class="store.running ? 'text-sky-300' : 'text-slate-400'">{{ activeStepLabel }}</p><p class="mt-1 font-mono text-xs text-slate-500">{{ completedSteps }}/{{ displaySteps.length || 7 }} 个步骤完成</p></div></header>
        <div class="grid gap-0 lg:grid-cols-[1.25fr_.75fr]"><div class="p-4"><div v-if="displaySteps.length" class="grid gap-2 sm:grid-cols-2 xl:grid-cols-3"><div v-for="step in displaySteps" :key="step.step" class="live-step" :class="step.status"><span class="step-dot">{{ stateIcon(step.status) }}</span><div class="min-w-0"><p class="truncate text-xs font-semibold">{{ step.step }}</p><p class="mt-1 truncate text-[11px] opacity-70"><span v-if="step.status === 'running'" class="running-signal">正在执行</span>{{ stateText(step.status, step.message) }}</p></div></div></div><div v-else class="grid min-h-[164px] place-items-center text-center"><div><div class="mx-auto grid h-11 w-11 place-items-center rounded-xl border border-sky-400/30 bg-sky-400/10 text-xl text-sky-300">◇</div><p class="mt-3 text-sm font-medium text-slate-200">等待开始构建</p><p class="mt-1 text-xs text-slate-500">开始后会展示每一步的真实执行状态</p></div></div></div>
          <div class="border-t border-slate-700/80 bg-[#070d18] p-4 lg:border-l lg:border-t-0"><div class="mb-3 flex items-center justify-between"><p class="text-xs font-semibold text-slate-300">实时日志</p><span class="font-mono text-[11px] text-slate-500">{{ store.logs.length }} 条</span></div><div class="max-h-[190px] space-y-2 overflow-auto font-mono text-[11px] leading-5"><p v-for="log in latestLogs" :key="log.id" :class="log.level === 'error' ? 'text-red-300' : log.level === 'success' ? 'text-emerald-300' : 'text-slate-400'">[{{ log.time }}] {{ log.message }}</p><p v-if="!latestLogs.length" class="text-slate-600">等待任务日志…</p></div></div>
        </div><footer class="flex flex-wrap items-center justify-between gap-2 border-t border-slate-700/80 bg-[#0d1727] px-4 py-2.5 text-xs"><span class="text-slate-400">目标 SVN：<b class="font-medium text-sky-200">{{ targetPath }}</b></span><span v-if="store.running" class="rounded-full bg-sky-400/10 px-2 py-1 text-sky-300">运行中，请保持页面开启</span></footer>
      </section>
    </div>

    <div v-if="pickerVisible" class="fixed inset-0 z-40 grid place-items-center bg-slate-950/40 p-4" @click.self="pickerVisible = false"><section class="w-full max-w-lg overflow-hidden rounded-xl bg-white shadow-2xl"><header class="border-b border-slate-100 px-5 py-4"><h3 class="text-base font-bold text-slate-900">{{ pickerTitle }}</h3><p class="mt-1 text-xs text-slate-500">输入关键字筛选，点击即可选中</p></header><div class="p-4"><input v-model.trim="pickerQuery" name="svnSearch" class="search-input" autofocus placeholder="搜索名称或订单号"><div class="mt-3 max-h-80 overflow-auto"><button v-for="item in filteredPickerItems" :key="item" class="picker-item" @click="choosePickerItem(item)">{{ item }}</button><p v-if="!filteredPickerItems.length" class="py-8 text-center text-sm text-slate-500">未找到匹配项</p></div></div></section></div>

    <div v-if="projectPickerVisible" class="fixed inset-0 z-40 grid place-items-center bg-slate-950/40 p-4" @click.self="projectPickerVisible = false"><section class="flex max-h-[82vh] w-full max-w-3xl flex-col overflow-hidden rounded-xl bg-white shadow-2xl"><header class="border-b border-slate-100 px-5 py-4"><h3 class="text-base font-bold text-slate-900">选择项目与分支</h3><p class="mt-1 text-xs text-slate-500">勾选项目后，在同一行确认该项目的分支。</p></header><div class="p-4"><input v-model.trim="projectQuery" name="projectSearch" class="search-input" placeholder="搜索项目名称"><div class="mt-3 max-h-[48vh] overflow-auto rounded-lg border border-slate-200"><div v-for="project in filteredProjects" :key="project.projectName" class="flex flex-wrap items-center gap-3 border-b border-slate-100 px-3 py-2.5 last:border-0"><input :id="`project-${project.projectName}`" class="h-4 w-4 accent-blue-600" type="checkbox" :checked="Boolean(draftBranches[project.projectName])" @change="toggleDraftProject(project)"><label :for="`project-${project.projectName}`" class="min-w-0 flex-1 cursor-pointer truncate text-sm font-semibold text-slate-800">{{ project.projectName }}</label><select v-model="draftBranches[project.projectName]" :name="`branch-${project.projectName}`" class="project-branch" :disabled="!draftBranches[project.projectName]"><option value="">选择分支</option><option v-for="branch in project.branches" :key="branch" :value="branch">{{ branch }}</option></select></div><p v-if="!filteredProjects.length" class="py-8 text-center text-sm text-slate-500">未找到项目</p></div></div><footer class="flex items-center justify-between border-t border-slate-100 px-5 py-3"><span class="text-xs text-slate-500">已选择 {{ draftCount }} 个项目</span><div class="flex gap-2"><button class="text-sm text-slate-500 hover:text-slate-800" @click="projectPickerVisible = false">取消</button><button class="secondary-btn" :disabled="!draftCount" @click="saveProjects">确认选择</button></div></footer></section></div>
  </main>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useAppStore } from '@/stores/appStore'
import { ipc } from '@/services/ipc'
import { refreshProjects } from '@/composables/useProjects'
import { saveConfig } from '@/composables/useConfig'
import { startRun, stopRun } from '@/composables/usePipeline'
import type { ProjectInfo, StepState } from '@/types'

type SelectedProject = { name: string; branch: string; svnLeaf: string }
const store = useAppStore()
const hospitalName = ref(store.config?.form.hospitalName || '')
const orderNo = ref(store.config?.form.orderNo || '')
const selectedProjects = ref<SelectedProject[]>([])
const pickerVisible = ref(false); const pickerKind = ref<'hospital' | 'order'>('hospital'); const pickerTitle = ref(''); const pickerItems = ref<string[]>([]); const pickerQuery = ref('')
const projectPickerVisible = ref(false); const projectQuery = ref(''); const draftBranches = reactive<Record<string, string>>({})
const activeState = computed(() => {
  const states = Object.values(store.projectStates)
  return states.find((state) => state.status === 'running') || states[states.length - 1]
})
const activeSelection = computed(() => selectedProjects.value.find((item) => item.name === activeState.value?.projectName) || selectedProjects.value[0])
const activeProjectName = computed(() => activeSelection.value?.name || '等待选择项目'); const activeBranch = computed(() => activeSelection.value?.branch || '—')
const displaySteps = computed<StepState[]>(() => activeState.value?.steps || []); const completedSteps = computed(() => displaySteps.value.filter((step) => step.status === 'done' || step.status === 'skipped').length); const activeStepLabel = computed(() => activeState.value?.currentStep || (store.running ? '正在准备任务…' : '准备就绪'))
const targetPath = computed(() => `SVN / ${hospitalName.value || '未选择医院'} / ${orderNo.value || '未选择订单'}`)
const latestLogs = computed(() => store.logs.slice(-8).map((log, index) => ({ id: `${log.timestamp}-${index}`, level: log.level, message: log.message, time: new Date(log.timestamp).toLocaleTimeString('zh-CN', { hour12: false }) })))
const filteredPickerItems = computed(() => pickerItems.value.filter((item) => item.toLowerCase().includes(pickerQuery.value.toLowerCase()))); const filteredProjects = computed(() => store.projects.filter((project) => project.projectName.toLowerCase().includes(projectQuery.value.toLowerCase()))); const draftCount = computed(() => Object.values(draftBranches).filter(Boolean).length)
function openProjectPicker() {
  Object.keys(draftBranches).forEach((name) => { draftBranches[name] = '' })
  projectQuery.value = ''
  selectedProjects.value.forEach((item) => { draftBranches[item.name] = item.branch })
  projectPickerVisible.value = true
}
function toggleDraftProject(project: ProjectInfo) { draftBranches[project.projectName] = draftBranches[project.projectName] ? '' : (project.currentBranch || project.branches[0] || '') }
function saveProjects() { selectedProjects.value = store.projects.flatMap((project) => draftBranches[project.projectName] ? [{ name: project.projectName, branch: draftBranches[project.projectName], svnLeaf: project.defaultSvnLeaf || '' }] : []); projectPickerVisible.value = false }
function removeProject(name: string) { selectedProjects.value = selectedProjects.value.filter((item) => item.name !== name); draftBranches[name] = '' }
async function openSvnPicker(kind: 'hospital' | 'order') { const config = store.config; if (!config) return; try { const url = kind === 'hospital' ? config.svnRootUrl : `${config.svnRootUrl.replace(/\/$/, '')}/${encodeURIComponent(hospitalName.value)}`; pickerItems.value = await ipc.svnList(config.tools.svn || 'svn', url, config.form.svnUsername, config.form.svnPassword); pickerKind.value = kind; pickerTitle.value = kind === 'hospital' ? '搜索并选择医院' : '搜索并选择订单号'; pickerQuery.value = ''; pickerVisible.value = true } catch (error) { store.showToast(`读取 SVN 列表失败：${error instanceof Error ? error.message : String(error)}`, 'error') } }
function choosePickerItem(item: string) { if (pickerKind.value === 'hospital') { hospitalName.value = item; orderNo.value = '' } else orderNo.value = item; pickerVisible.value = false }
function queueLabel(name: string) { const state = store.projectStates[name]; if (state?.status === 'done') return '已完成'; if (state?.status === 'failed') return '失败'; if (state?.status === 'running') return activeStepLabel.value; if (store.running) return `排队中 #${selectedProjects.value.findIndex((item) => item.name === name) + 1}`; return '已确认' }
function queueClass(name: string) { const status = store.projectStates[name]?.status; return status === 'done' ? 'text-emerald-600' : status === 'failed' ? 'text-red-600' : status === 'running' ? 'text-blue-600' : 'text-slate-400' }
function stateIcon(status: StepState['status']) { return status === 'done' || status === 'skipped' ? '✓' : status === 'failed' ? '!' : status === 'running' ? '●' : '○' }
function stateText(status: StepState['status'], message?: string) { return message || (status === 'done' ? '已完成' : status === 'failed' ? '执行失败' : status === 'running' ? '执行中' : '等待执行') }
async function startBuild() { const config = store.config; if (!config) return; if (!hospitalName.value || !orderNo.value || !selectedProjects.value.length) return store.showToast('请先选择医院、订单号和至少一个项目', 'warning'); if (!config.form.svnUsername || !config.form.svnPassword) return store.showToast('请先在设置中配置 SVN 账号和密码', 'warning'); config.form.hospitalName = hospitalName.value; config.form.orderNo = orderNo.value; config.uploadAfterBuild = true; config.uploadToServer = false; await saveConfig(config); await startRun({ config, mode: 'svn', projects: selectedProjects.value.map((item) => ({ name: item.name, branch: item.branch, svn_leaf: item.svnLeaf, enabled: true })) }) }
onMounted(async () => { if (store.config && !store.projects.length) await refreshProjects() })
</script>

<style scoped>
.selection-trigger{display:flex;align-items:center;gap:8px;height:40px;border:1px solid #dbe3ee;border-radius:8px;padding:0 11px;background:#fff;text-align:left;transition:.15s}.selection-trigger:hover:not(:disabled){border-color:#93c5fd;background:#f8fbff}.selection-trigger:disabled{opacity:.55;cursor:not-allowed}.selection-trigger span{color:#64748b;font-size:12px}.selection-trigger b{min-width:0;flex:1;overflow:hidden;color:#1e293b;font-size:13px;text-overflow:ellipsis;white-space:nowrap}.selection-trigger i{color:#64748b;font-style:normal}.secondary-btn{height:38px;border:1px solid #bfdbfe;border-radius:8px;background:#fff;padding:0 12px;color:#2563eb;font-size:13px;font-weight:600}.secondary-btn:hover:not(:disabled){background:#eff6ff}.secondary-btn:disabled{opacity:.45;cursor:not-allowed}.branch-pill{max-width:45%;overflow:hidden;border:1px solid #dbeafe;border-radius:6px;background:#f8fbff;padding:4px 8px;color:#2563eb;font-family:ui-monospace,SFMono-Regular,monospace;font-size:12px;text-overflow:ellipsis;white-space:nowrap}.live-step{position:relative;display:flex;align-items:center;gap:8px;overflow:hidden;border:1px solid #25334a;border-radius:8px;padding:9px;color:#94a3b8}.live-step.running{border-color:#38bdf8;background:#0f2748;color:#eff6ff;box-shadow:0 0 0 1px rgb(56 189 248 / 18%),0 0 18px rgb(37 99 235 / 32%)}.live-step.running::after{position:absolute;inset:0;content:'';background:linear-gradient(100deg,transparent 35%,rgb(125 211 252 / 22%) 50%,transparent 65%);transform:translateX(-120%);animation:scan-step 1.7s linear infinite;pointer-events:none}.live-step.done,.live-step.skipped{border-color:#14532d;background:#0c241d;color:#bbf7d0}.live-step.failed{border-color:#7f1d1d;background:#2a1319;color:#fecaca}.step-dot{position:relative;z-index:1;display:grid;height:22px;width:22px;flex:0 0 auto;place-items:center;border-radius:50%;background:#1e293b;font-size:11px}.running .step-dot{background:#2563eb;animation:pulse-dot 1.2s infinite}.done .step-dot,.skipped .step-dot{background:#047857}.failed .step-dot{background:#b91c1c}.running-signal{display:inline-block;margin-right:5px;border-radius:3px;background:#0ea5e9;padding:1px 4px;color:#fff;font-size:10px;font-weight:700;letter-spacing:.04em;animation:signal-blink 1.2s ease-in-out infinite}@keyframes pulse-dot{50%{box-shadow:0 0 0 6px rgb(56 189 248 / 12%),0 0 17px rgb(56 189 248 / 95%)}}@keyframes scan-step{to{transform:translateX(120%)}}@keyframes signal-blink{50%{opacity:.55}}@media (prefers-reduced-motion:reduce){.live-step.running::after,.running .step-dot,.running-signal{animation:none}}
.search-input{width:100%;height:40px;border:1px solid #cbd5e1;border-radius:8px;padding:0 12px;outline:none;font-size:14px}.search-input:focus{border-color:#2563eb;box-shadow:0 0 0 3px rgb(37 99 235 / 12%)}.picker-item{display:block;width:100%;border-radius:7px;padding:9px 10px;text-align:left;font-size:14px;color:#334155}.picker-item:hover{background:#eff6ff;color:#1d4ed8}.project-branch{width:220px;height:34px;border:1px solid #dbe3ee;border-radius:7px;padding:0 8px;color:#334155;font-size:12px}.project-branch:disabled{opacity:.45}
</style>
